-- Create the notes table if it doesn't exist (already handled previously)
-- Ensure user_id column exists (already handled previously)
-- 1. Create folders table
create table if not exists folders (
  id bigint generated by default as identity primary key,
  name text not null,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add folder_id to notes
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'notes' and column_name = 'folder_id') then
    alter table notes add column folder_id bigint references folders(id);
  end if;
end $$;


-- 3. RLS for Folders
alter table folders enable row level security;

-- Drop existing policies if any to avoid conflicts
drop policy if exists "Users can create their own folders" on folders;
drop policy if exists "Users can view their own folders" on folders;
drop policy if exists "Users can update their own folders" on folders;
drop policy if exists "Users can delete their own folders" on folders;

create policy "Users can create their own folders"
on folders for insert
with check (auth.uid() = user_id);

create policy "Users can view their own folders"
on folders for select
using (auth.uid() = user_id);

create policy "Users can update their own folders"
on folders for update
using (auth.uid() = user_id);

create policy "Users can delete their own folders"
on folders for delete
using (auth.uid() = user_id);


-- 4. RLS for Notes (Update existing ones to be safe, though existing logic handles user_id)
-- Just ensuring `notes` policies are still valid (they rely on user_id, not folder_id, so we are good).
